### ISSUE TITLE
[SM-11] Update README.md for devs

### ISSUE THREAD

**Issue by teddy-cb** [shanehuff/samir#14]
What to do:

- [ ] How to set up dev env. If not much different from Laravel setup, a link to their docs would be enough.
- [ ] What/how to config. Mostly related to some private keys or other env values.
- [ ] How to deploy. 
- [ ] (Maybe) How to test.
- [ ] (Maybe) A demo site, which should be only fake or test data.
- [ ] (Maybe) A diagram to illustrate how the app works/interacts with Binance / 3 Commas. We can use Mermaid for this purpose https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/

**Comment by 0xSonaMaka** [comment]
gm!

**Comment by teddy-cb** [comment]
Just added this item: 

>  (Maybe) A diagram to illustrate how the app works/interacts with Binance / 3 Commas. We can use Mermaid for this purpose https://github.blog/2022-02-14-include-diagrams-markdown-files-mermaid/
